local err = require("santoku.error")
local error = err.error
local assert = err.assert
local pcall = err.pcall

local fs = require("santoku.fs")
local sys = require("santoku.system")
local env = require("santoku.env")

local str = require("santoku.string")
local arr = require("santoku.array")
local printf = str.printf
local startswith = str.startswith

local site = "https://santoku.dev"
local pack_url = site .. "/skills.txt"
local agents_url = site .. "/AGENTS.md"
local agents_marker = "<!-- generated by toku skills from " .. agents_url .. " -->"
local pack_header = "santoku-skills 1"
local record = ">>> "
local manifest_name = ".toku-skills.lua"

local function have (cmd)
  return (pcall(sys.execute,
    { "sh", "-c", "command -v " .. cmd .. " >/dev/null 2>&1" }))
end

local function download_args (dest, url)
  if have("curl") then
    return { "curl", "-fsSL", "-o", dest, "--", url }
  elseif have("wget") then
    return { "wget", "-q", "-O", dest, "--", url }
  else
    return error("no downloader found: install curl or wget")
  end
end

local function fetch (url)
  local tmp = fs.tmpname()
  local ok = pcall(sys.execute, download_args(tmp, url))
  if not ok then
    fs.rm(tmp, true)
    return error("unable to fetch", url)
  end
  local body = fs.readfile(tmp)
  fs.rm(tmp, true)
  return body
end

local function split_lines (s)
  local out, pos = {}, 1
  while pos <= #s do
    local i = str.find(s, "\n", pos, true)
    if not i then
      arr.push(out, str.sub(s, pos))
      return out
    end
    arr.push(out, str.sub(s, pos, i - 1))
    pos = i + 1
  end
  return out
end

local function unpack_pack (body)
  local ls = split_lines(body)
  if ls[1] ~= pack_header then
    return error("unexpected skills bundle header", pack_url, ls[1])
  end
  local out, cur = {}, nil
  for i = 2, #ls do
    local line = ls[i]
    if startswith(line, record) then
      local name = str.sub(line, #record + 1)
      if not str.match(name, "^[a-z][a-z0-9%-]*$") or #name > 64 then
        return error("skills bundle names an invalid skill", name)
      end
      cur = { name = name, lines = {} }
      arr.push(out, cur)
    elseif cur then
      arr.push(cur.lines, line)
    else
      return error("skills bundle has content before its first record", line)
    end
  end
  if #out == 0 then
    return error("skills bundle carries no skills", pack_url)
  end
  for i = 1, #out do
    local skill = out[i]
    skill.source = arr.concat(skill.lines, "\n") .. "\n"
    skill.lines = nil
    if not startswith(skill.source, "---\n") then
      return error("skill does not open with a frontmatter block", skill.name)
    end
  end
  return out
end

local function read_manifest (fp)
  if not fs.isfile(fp) then
    return {}
  end
  local m = fs.runfile(fp)
  assert(type(m) == "table",
    "installed skills manifest is not a table, remove it and run toku skills again", fp)
  return m
end

local function write_manifest (fp, skills)
  local out = { "return {\n" }
  for i = 1, #skills do
    arr.push(out, str.format("  %q,\n", skills[i].name))
  end
  arr.push(out, "}\n")
  fs.writefile(fp, arr.concat(out))
end

local function remove_dir (dir)
  for fp in fs.files(dir, true) do
    fs.rm(fp)
  end
  fs.rmdirs(dir)
end

local function install_claude (skills, root, dry)
  local dir = fs.join(root, "skills")
  local manifest_fp = fs.join(dir, manifest_name)
  local previous = read_manifest(manifest_fp)
  local keep = {}
  for i = 1, #skills do
    local skill = skills[i]
    keep[skill.name] = true
    local fp = fs.join(dir, skill.name, "SKILL.md")
    if dry then
      printf("[skills]\twould write %s\n", fp)
    else
      fs.mkdirp(fs.dirname(fp))
      fs.writefile(fp, skill.source)
      printf("[skills]\twrote %s\n", fp)
    end
  end
  for i = 1, #previous do
    local name = previous[i]
    local stale = fs.join(dir, name)
    if not keep[name] and fs.isdir(stale) then
      if dry then
        printf("[skills]\twould remove %s (no longer published)\n", stale)
      else
        remove_dir(stale)
        printf("[skills]\tremoved %s (no longer published)\n", stale)
      end
    end
  end
  if dry then
    printf("[skills]\twould write %s\n", manifest_fp)
  else
    write_manifest(manifest_fp, skills)
  end
end

local function install_codex (agents, root, force, dry)
  local fp = fs.join(root, "AGENTS.md")
  if fs.isfile(fp) and not force then
    if not startswith(fs.readfile(fp), agents_marker) then
      return error(
        "refusing to overwrite an AGENTS.md that toku skills did not write, " ..
        "move it aside or pass --force", fp)
    end
  end
  if dry then
    printf("[skills]\twould write %s\n", fp)
    return
  end
  fs.mkdirp(root)
  fs.writefile(fp, agents)
  printf("[skills]\twrote %s\n", fp)
end

local function install (opts)
  opts = opts or {}
  local home = env.var("HOME")
  local claude_dir = opts.claude_dir or fs.join(home, ".claude")
  local codex_dir = opts.codex_dir or fs.join(home, ".codex")
  printf("[skills]\tfetching %s\n", pack_url)
  local skills = unpack_pack(fetch(pack_url))
  printf("[skills]\tfetching %s\n", agents_url)
  local agents = fetch(agents_url)
  if not startswith(agents, agents_marker) then
    return error("fetched AGENTS.md is missing its generated marker", agents_url)
  end
  install_claude(skills, claude_dir, opts.dry_run)
  install_codex(agents, codex_dir, opts.force, opts.dry_run)
  printf("[skills]\t%d skills, Claude Code reads %s, Codex reads %s\n",
    #skills, fs.join(claude_dir, "skills"), fs.join(codex_dir, "AGENTS.md"))
  printf("[skills]\tfor Claude Code the plugin is the richer path:\n")
  printf("[skills]\t  /plugin marketplace add birchpointswe/santoku-docs\n")
  printf("[skills]\t  /plugin install santoku@santoku\n")
end

return {
  site = site,
  pack_url = pack_url,
  agents_url = agents_url,
  install = install,
}
